#cloud-config
#
package_upgrade: true
packages:
  - language-pack-en
  - socat
  - conntrack
  - ipset
  - debconf-utils
  - containerd
  - glusterfs-client
bootcmd:
  - echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
apt:
  sources:
    gluster.list:
      source: "ppa:gluster/glusterfs-6"
    raptor.key:
      keyid: "FEEA9169307EA071"
    cloud-raptor.key:
      keyid: "8B57C5C2836F4BEB"
    kubernetes.list:
      source: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
