#cloud-config
#
package_upgrade: true
packages:
  - language-pack-en
  - socat
  - conntrack
  - ipset
  - debconf-utils
  - glusterfs-client
bootcmd:
  - echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
