#!/bin/bash

set -e
APT_GET="sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_SUSPEND=1 apt-get -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef -qq -y"

echo "Waiting for base package installation to complete"
cloud-init status --wait >/dev/null

echo "Adding repositories"

rel=${kubernetes_release}
curl -fsSL https://pkgs.k8s.io/core:/stable:/v$${rel%.*}/deb/Release.key | sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v$${rel%.*}/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo rm -f /etc/apt/sources.list.d/kubernetes-old.list /etc/apt/sources.list.d/docker.list /usr/share/keyrings/kubernetes.gpg

echo "Installing versioned packages"

$${APT_GET} update
if ! kube_rel=$(apt-cache madison "kubeadm" | grep -Po "(?<= )${kubernetes_release}[^ ]*")
then
    kube_rel="${kubernetes_release}"
fi
if ! cri_rel=$(apt-cache madison "cri-tools" | grep -Po "(?<= )${critools_release}[^ ]*")
then
    cri_rel="${critools_release}"
fi
$${APT_GET} --allow-change-held-packages install \
    containerd \
	kubeadm=$${kube_rel} \
	kubectl=$${kube_rel} \
	kubelet=$${kube_rel} \
	cri-tools=$${cri_rel}
sudo apt-mark hold kubeadm kubectl kubelet cri-tools
