#!/bin/bash

set -e
APT_GET="sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_SUSPEND=1 apt-get -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef -qq -y"

echo "Waiting for base package installation to complete"
cloud-init status --wait >/dev/null

echo "Adding repositories"

curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/kubernetes.gpg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo rm -f /etc/apt/sources.list.d/docker.list
#echo "deb [signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

echo "Installing versioned packages"

$${APT_GET} update
$${APT_GET} --allow-change-held-packages install \
    containerd \
	kubeadm=${kubernetes_release}-00 \
	kubectl=${kubernetes_release}-00 \
	kubelet=${kubernetes_release}-00 \
	cri-tools=${critools_release}-00
sudo apt-mark hold kubeadm kubectl kubelet cri-tools
