apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-test
  labels:
    app: local-test
spec:
  serviceName: "local-service"
  selector:
    matchLabels:
      app: local-test
  replicas: 3
  template:
    metadata:
      labels:
        app: local-test
    spec:
      containers:
      - name: test-container
        image: gcr.io/google_containers/busybox:1.24
        command: 
        - "/bin/sh"
        args:
        - "-c"
        - "count=0; count_file=\"/usr/test-pod/count\"; test_file=\"/usr/test-pod/test_file\"; if [ -e $count_file ]; then count=$(cat $count_file); fi; echo $((count+1)) > $count_file; while [ 1 ]; do date >> $test_file; echo \"This is $MY_POD_NAME, count=$(cat $count_file)\" >> $test_file; sleep 10; done"
        volumeMounts:
        - name: local-vol
          mountPath: /usr/test-pod
        env:
        - name: MY_POD_NAME
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name
      securityContext:
        fsGroup: 1234
  volumeClaimTemplates:
  - metadata:
      name: local-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "openebs-hostpath"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-test-reader
  labels:
    app: local-test-reader
spec:
  selector:
    matchLabels:
      app: local-test-reader
  replicas: 1
  template:
    metadata:
      labels:
        app: local-test-reader
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: reader
        image: gcr.io/google_containers/busybox:1.24
        command: 
        - "/bin/sh"
        args:
        - "-c"
        - "tail -f /usr/test-pod/test_file"
        volumeMounts:
        - name: local-vol
          mountPath: /usr/test-pod
      volumes:
      - name: local-vol
        persistentVolumeClaim: 
          claimName: "local-vol-local-test-0"
