#!/bin/sh

set -eu

# Retries a command on failure.
# $1 - the max number of attempts
# $2... - the command to run
retry() {
    local max_attempts="$${1}"; shift
    local attempt_num=1

    until "$${@}"
    do
        if [ "$${attempt_num}" -eq "$${max_attempts}" ]
        then
            echo "Attempt $${attempt_num} failed and there are no more attempts l
eft!"
            return 1
        else
            echo "Attempt $${attempt_num} failed! Trying again in $${attempt_num}
seconds..."
            sleep $(( attempt_num=attempt_num + 1 ))
        fi
    done
}

install_etcd() {
    rm -rf /tmp/etcd
    mkdir -p /tmp/etcd
    curl -sf https://api.github.com/repos/etcd-io/etcd/releases/latest \
        | grep browser_download_url \
        | grep linux-amd64 \
        | cut -d '"' -f 4 \
        | wget -P /tmp/etcd -qi -
    tar -C /tmp/etcd -xf /tmp/etcd/*.tar.gz
    sudo install --compare --mode=0755 -D  --target-directory "/opt/sbin" /tmp/etcd/etcd*-linux-amd64/etcd* 
    rm -rf /tmp/etcd
}

install_etcd
