#!/bin/bash

set -eu

etcdctl="sudo /opt/etcd/bin/etcdctl \
                    --cacert=/etc/kubernetes/pki/etcd/ca.crt \
                    --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt \
                    --key=/etc/kubernetes/pki/etcd/healthcheck-client.key"
endpoints="--endpoints=${all_endpoints}"

# Retries a command on failure.
# $1 - the max number of attempts
# $2... - the command to run
retry() {
    local max_attempts="$${1}"; shift
    local attempt_num=1

    until "$${@}"
    do
        if [ "$${attempt_num}" -eq "$${max_attempts}" ]
        then
            echo "Attempt $${attempt_num} failed and there are no more attempts l
eft!"
            return 1
        else
            echo "Attempt $${attempt_num} failed! Trying again in $${attempt_num}
seconds..."
            sleep $(( attempt_num=attempt_num + 1 ))
        fi
    done
}

install_etcd_config() {
    local initial_cluster_state="$1"
    cat <<EOF | sudo tee /etc/opt/etcd/etcd.conf 
# This is the configuration file for the etcd server.

name: ${id}

# Path to the data directory.
data-dir: /var/opt/etcd

# Path to the dedicated wal directory.
# wal-dir:

# Number of committed transactions to trigger a snapshot to disk.
snapshot-count: 10000

# Time (in milliseconds) of a heartbeat interval.
# heartbeat-interval: 100

# Time (in milliseconds) for an election to timeout.
# election-timeout: 1000

# Raise alarms when backend size exceeds the given quota. 0 means use the
# default quota.
# quota-backend-bytes: 0

# List of comma separated URLs to listen on for peer traffic.
listen-peer-urls: ${peer_urls}

# List of comma separated URLs to listen on for client traffic.
listen-client-urls: https://[::1]:2379,https://127.0.0.1:2379,${client_urls}

# List of additional URLs to listen on that will respond to both the /metrics and /health endpoints
listen-metrics-urls: http://[::1]:2381,http://127.0.0.1:2381

# Maximum number of snapshot files to retain (0 is unlimited).
# max-snapshots: 5

# Maximum number of wal files to retain (0 is unlimited).
# max-wals: 5

# Comma-separated white list of origins for CORS (cross-origin resource sharing).
# cors:

# List of this member's peer URLs to advertise to the rest of the cluster.
# The URLs needed to be a comma-separated list.
initial-advertise-peer-urls: ${peer_urls}

# List of this member's client URLs to advertise to the public.
# The URLs needed to be a comma-separated list.
advertise-client-urls: ${client_urls}

# Discovery URL used to bootstrap the cluster.
# discovery:

# Valid values include 'exit', 'proxy'
# discovery-fallback: 'proxy'

# HTTP proxy to use for traffic to discovery service.
# discovery-proxy:

# DNS domain used to bootstrap initial cluster.
# discovery-srv:

# Initial cluster configuration for bootstrapping.
initial-cluster: ${id}=${peer_urls}

# Initial cluster token for the etcd cluster during bootstrap.
initial-cluster-token: 'etcd-cluster'

# Initial cluster state ('new' or 'existing').
initial-cluster-state: $${initial_cluster_state}

# Reject reconfiguration requests that would cause quorum loss.
strict-reconfig-check: true

# Accept etcd V2 client requests
# enable-v2: false

# Enable runtime profiling data via HTTP server
# enable-pprof: true

# Valid values include 'on', 'readonly', 'off'
# proxy: 'off'

# Time (in milliseconds) an endpoint will be held in a failed state.
# proxy-failure-wait: 5000

# Time (in milliseconds) of the endpoints refresh interval.
# proxy-refresh-interval: 30000

# Time (in milliseconds) for a dial to timeout.
# proxy-dial-timeout: 1000

# Time (in milliseconds) for a write to timeout.
# proxy-write-timeout: 5000

# Time (in milliseconds) for a read to timeout.
# proxy-read-timeout: 0

client-transport-security:
  # Path to the client server TLS cert file.
  cert-file: /etc/kubernetes/pki/etcd/server.crt

  # Path to the client server TLS key file.
  key-file: /etc/kubernetes/pki/etcd/server.key

  # Enable client cert authentication.
  client-cert-auth: true

  # Path to the client server TLS trusted CA cert file.
  trusted-ca-file: /etc/kubernetes/pki/etcd/ca.crt

  # Client TLS using generated certificates
  auto-tls: false

peer-transport-security:
  # Path to the peer server TLS cert file.
  cert-file: /etc/kubernetes/pki/etcd/peer.crt

  # Path to the peer server TLS key file.
  key-file: /etc/kubernetes/pki/etcd/peer.key

  # Enable peer client cert authentication.
  client-cert-auth: true

  # Path to the peer server TLS trusted CA cert file.
  trusted-ca-file: /etc/kubernetes/pki/etcd/ca.crt

  # Peer TLS using generated certificates.
  auto-tls: false

# Enable debug-level logging for etcd.
# debug: false

logger: zap

# Specify 'stdout' or 'stderr' to skip journald logging even when running under systemd.
# log-outputs: [stderr]

# Force to create a new one member cluster.
# force-new-cluster: false

auto-compaction-mode: periodic
auto-compaction-retention: "1"
EOF
}

install_etcd_systemd() {
    
    cat <<EOF | sudo tee /etc/systemd/system/etcd.service
[Unit]
Description=etcd service
Documentation=https://github.com/etcd-io/etcd
After=network.target

[Service]
User=etcd
Type=notify
ExecStart=/opt/etcd/bin/etcd --config-file /etc/opt/etcd/etcd.conf
Restart=always
RestartSec=5s
LimitNOFILE=40000
UMask=0077

[Install]
WantedBy=multi-user.target
EOF
}

install_etcd() {
    rm -rf /tmp/etcd
    mkdir -p /tmp/etcd
    local download="https://github.com/etcd-io/etcd/releases/download/"
    curl -sf https://api.github.com/repos/etcd-io/etcd/releases \
        | grep etcd-v3.4 \
        | grep browser_download_url \
        | grep linux-amd64 \
        | head -1 \
        | cut -d '"' -f 4 \
        | wget -P /tmp/etcd -qi -
    tar -C /tmp/etcd -xf /tmp/etcd/*.tar.gz
    sudo install --compare --mode=0755 -D  --target-directory "/opt/etcd/bin" /tmp/etcd/etcd*-linux-amd64/etcd* 
    rm -rf /tmp/etcd
}

local_health() {
    retry 10 $${etcdctl} endpoint health
}

activate_new_cluster() {
    echo "Setting up new cluster node $(hostname -s)"
    retry 5 sudo systemctl start etcd
    local_health
}

maintain_existing_cluster() {
    echo "Maintaining existing cluster"
    echo "Obtaining maintenance lock..."
    retry 10 $${etcdctl} $${endpoints} lock cluster_reconfig hostname
    $${etcdctl} $${endpoints} lock cluster_reconfig /bin/bash /tmp/reconfig-etcd  "${all_endpoints}" "${peer_urls}"
    echo "Unlocked"
}

echo "Installing Etcd"
sudo mkdir -p /opt/etcd/bin /etc/opt/etcd /var/opt/etcd /etc/kubernetes/pki/etcd
sudo useradd -s /sbin/nologin --system -U etcd || true
sudo chown -R etcd:etcd /var/opt/etcd /etc/kubernetes/pki/etcd
sudo chmod 0700 /var/opt/etcd
install_etcd
install_etcd_systemd
if [ -d /tmp/etcd-certs/etcd ]
then
    sudo install --compare --owner=etcd --group=etcd --mode=0600 -D --target-directory "/etc/kubernetes/pki/etcd" /tmp/etcd-certs/etcd/*.key
    sudo install --compare --owner=etcd --group=etcd --mode=0644 -D --target-directory "/etc/kubernetes/pki/etcd" /tmp/etcd-certs/etcd/*.crt
fi
sudo systemctl enable etcd

if [ "${bootstrap_node}" -a -z "$(sudo -u etcd ls -A /var/opt/etcd)" ]
then
    install_etcd_config "new"
    activate_new_cluster
else
    install_etcd_config "existing"
    maintain_existing_cluster
fi
