#!/bin/bash

set -e

newer_cert() {
        local source_prefix=$${1}
        local dest_prefix=$${2:-$${1}}
        local target_suffix=$${3:-crt}
        local pki_dir=/etc/kubernetes/pki

        for word in $${target_suffix} key
        do
		if sudo test $${source_prefix}.$${word} -nt $${pki_dir}/$${dest_prefix}.$${word}
		then
			return 0
		fi
        done
	return 1
}

# Retries a command on failure.
# $1 - the max number of attempts
# $2... - the command to run
retry() {
    local max_attempts="$${1}"; shift
    local attempt_num=1

    until "$${@}"
    do
        if [ "$${attempt_num}" -eq "$${max_attempts}" ]
        then
            echo "Attempt $${attempt_num} failed and there are no more attempts l
eft!"
            return 1
        else
            echo "Attempt $${attempt_num} failed! Trying again in $${attempt_num}
seconds..."
            sleep $(( attempt_num=attempt_num + 1 ))
        fi
    done
}

reset_if_newer_ca(){
	if newer_cert ca
	then
		echo "Resetting kubelet"
		sudo mv /etc/kubernetes/*.conf /etc/kubernetes/pki/ca.crt /tmp
		sudo systemctl stop kubelet
	fi
}

install() {
	retry 5 sudo systemctl enable iscsid
	retry 5 sudo systemctl start iscsid
	echo "Joining cluster"
	discovery_ca_cert_hash=$(openssl x509 -in $HOME/ca.crt -noout -pubkey |openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1)

	retry 5 sudo kubeadm join ${fqdn}:${service_port} --token ${boot_token} --discovery-token-ca-cert-hash sha256:$${discovery_ca_cert_hash}
}

ensure_docker_settings() {
	if [ ! -f /etc/docker/daemon.json ]
	then
		echo "Writing Updated Docker Configuration"
		cat <<EOF | sudo tee /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "live-restore": true,
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF
		sudo systemctl reload docker
		sudo mkdir -p /etc/systemd/system/docker.service.d
		sudo systemctl daemon-reload
	fi
}


upgrade() {
	if [ -f /var/run/docker.sock ]
	then
		ensure_docker_settings
	fi
	echo "Kubeadm installed worker node detected - checking for upgrade"
	sudo systemctl enable iscsid && sudo systemctl start iscsid
	sudo apt-get -qq update -y
	sudo apt-get -qq install -y debconf-utils lvm2
	echo "docker.io docker.io/restart select true" | sudo debconf-set-selections
	if sudo apt-get -qq install kubeadm=${kubernetes_release}-00
	then
		retry 5 sudo kubeadm upgrade node config --kubelet-version=${kubernetes_release}
		sudo apt-get -qq install \
			kubectl=${kubernetes_release}-00 \
			kubelet=${kubernetes_release}-00
	else
		echo "Failed to install kubeadm at version ${kubernetes_release}-00"
		echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show kubeadm)"
	fi
}

if [ -f /etc/kubernetes/pki/ca.crt ]
then
	reset_if_newer_ca
fi
if [ -f /etc/kubernetes/kubelet.conf ]
then
	upgrade
else
	install
fi
