#!/bin/bash

# Retries a command on failure.
# $1 - the max number of attempts
# $2... - the command to run
retry() {
    local max_attempts="$${1}"; shift
    local attempt_num=1

    until "$${@}"
    do
        if [ "$${attempt_num}" -eq "$${max_attempts}" ]
        then
            echo "Attempt $${attempt_num} failed and there are no more attempts l
eft!"
            return 1
        else
            echo "Attempt $${attempt_num} failed! Trying again in $${attempt_num}
seconds..."
            sleep $(( attempt_num=attempt_num + 1 ))
        fi
    done
}

ensure_docker_settings() {
	if [ ! -f /etc/docker/daemon.json ]
	then
		echo "Writing Updated Docker Configuration"
		cat <<EOF | sudo tee /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "live-restore": true,
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF
		sudo systemctl reload docker
		sudo mkdir -p /etc/systemd/system/docker.service.d
		sudo systemctl daemon-reload
	fi
}

ensure_updated_apt_keys() {
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
}

echo "Ensuring installation has completed"
cloud-init status --wait >/dev/null

echo "Checking for upgrades"
if [ -f /var/run/docker.sock ]
then
	ensure_docker_settings
fi

sudo systemctl enable iscsid && sudo systemctl start iscsid
ensure_updated_apt_keys
sudo apt-get -qq update -y
sudo apt-get -qq install -y debconf-utils lvm2
echo "docker.io docker.io/restart select true" | sudo debconf-set-selections
echo "Upgrading kubeadm"
if ! retry 5 sudo apt-get -qq -y --allow-change-held-packages install kubeadm="${kubernetes_release}-00"
then
	sudo apt-mark hold kubeadm
	echo "Failed to install kubeadm at version ${kubernetes_release}-00"
	echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show kubeadm)"
	exit 2
fi
sudo apt-mark hold kubeadm
echo "Upgrading worker node"
case ${kubernetes_release} in
    1.2[01].*)
		retry 5 sudo kubeadm upgrade node
		;;
	1.1[789].*)
		retry 5 sudo kubeadm upgrade node
		;;
	1.1[56].*)
		retry 5 sudo kubeadm upgrade node --certificate-renewal
		;;
	1.14.*)
		retry 5 sudo kubeadm upgrade node config --kubelet-version="${kubernetes_release}"
		;;
    *)
        echo "Unsupported version ${kubernetes_release}"
        exit 1
        ;;
esac
echo "Upgrading kubelet"
retry 5 sudo apt-get -qq -y --allow-change-held-packages install \
	kubectl="${kubernetes_release}-00" \
	kubelet="${kubernetes_release}-00"
sudo apt-mark hold kubelet kubectl
retry 5 sudo systemctl restart kubelet
