#!/bin/bash

APT_GET="sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_SUSPEND=1 apt-get -qq -y"

# Retries a command on failure.
# $1 - the max number of attempts
# $2... - the command to run
retry() {
    local max_attempts="$${1}"; shift
    local attempt_num=1

    until "$${@}"
    do
        if [ "$${attempt_num}" -eq "$${max_attempts}" ]
        then
            echo "Attempt $${attempt_num} failed and there are no more attempts l
eft!"
            return 1
        else
            echo "Attempt $${attempt_num} failed! Trying again in $${attempt_num}
seconds..."
            sleep $(( attempt_num=attempt_num + 1 ))
        fi
    done
}

ensure_docker_settings() {
	if [ ! -f /etc/docker/daemon.json ]
	then
		echo "Writing Updated Docker Configuration"
		cat <<EOF | sudo tee /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "live-restore": true,
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF
		sudo systemctl reload docker
		sudo mkdir -p /etc/systemd/system/docker.service.d
		sudo systemctl daemon-reload
	fi
}

ensure_updated_apt_keys() {
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/kubernetes.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
}

echo "Ensuring installation has completed"
cloud-init status --wait >/dev/null

echo "Checking for upgrades"
if [ -f /var/run/docker.sock ]
then
	ensure_docker_settings
fi

sudo systemctl enable iscsid && sudo systemctl start iscsid
ensure_updated_apt_keys
$${APT_GET} update
$${APT_GET} install debconf-utils lvm2 nfs-common
echo "docker.io docker.io/restart select true" | sudo debconf-set-selections
# Upgrade cri-tools before upgrading kubeadm to avoid CRI API incompatibility
echo "Upgrading cri-tools"
if ! retry 5 sudo apt-get -qq -y --allow-change-held-packages --allow-downgrades install cri-tools="${critools_release}-00"
then
	sudo apt-mark hold cri-tools
	echo "Failed to install cri-tools at version ${critools_release}-00"
	echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show cri-tools)"
	return 2
fi
sudo apt-mark hold cri-tools
echo "Upgrading kubeadm"
if ! retry 5 $${APT_GET} --allow-change-held-packages --allow-downgrades install kubeadm="${kubernetes_release}-00"
then
	sudo apt-mark hold kubeadm
	echo "Failed to install kubeadm at version ${kubernetes_release}-00"
	echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show kubeadm)"
	exit 2
fi
sudo apt-mark hold kubeadm
echo "Upgrading worker node"
case ${kubernetes_release} in
    1.2[23456].*)
		retry 5 sudo kubeadm upgrade node
		;;
    *)
        echo "Unsupported version ${kubernetes_release}"
        exit 1
        ;;
esac
echo "Upgrading kubelet"
retry 5 $${APT_GET} --allow-change-held-packages --allow-downgrades install \
	kubectl="${kubernetes_release}-00" \
	kubelet="${kubernetes_release}-00"
sudo apt-mark hold kubelet kubectl
retry 5 sudo systemctl restart kubelet
