apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: load-balancer-example
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      run: load-balancer-example
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - name: hello-world
          containerPort: 8080
          protocol: TCP
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: load-balancer-example
spec:
  minAvailable: 1
  selector:
    matchLabels:
      run: load-balancer-example
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: load-balancer-example
  name: example-service
spec:
  selector:
    run: load-balancer-example
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: hello-world
