#!/bin/bash

set -e

install_cert() {
	local source_prefix=$$1
	local dest_prefix=$${2:-$$1}
        local pki_dir=/etc/kubernetes/pki

	for word in crt key
	do
		sudo cp $${source_prefix}.$${word} $${pki_dir}/$${dest_prefix}.$${word}
	done
	sudo chmod 0600 $${pki_dir}/$${dest_prefix}.key
	rm $${source_prefix}.key
}

echo "Joining cluster"
discovery_ca_cert_hash=$(openssl x509 -in $HOME/ca.crt -noout -pubkey |openssl rsa -pubin -outform DER 2>/dev/null | sha256sum | cut -d' ' -f1)

sudo kubeadm join ${v6_hostname}:6443 --token ${boot_token} --discovery-token-ca-cert-hash sha256:$${discovery_ca_cert_hash}
