#!/bin/bash

set -e

cat <<EOF | sudo tee /var/lib/kubelet/kubelet-config.yaml
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
runtimeRequestTimeout: "15m"
staticPodPath: "/etc/kubernetes/manifests"
syncFrequency: "30s"
fileCheckFrequency: "30s"
maxPods: 10
authentication:
 webhook:
   enabled: false
 anonymous:
   enabled: true
authorization:
  mode: AlwaysAllow
EOF
cat <<EOF | sudo tee /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=containerd.service
Requires=containerd.service

[Service]
ExecStart=/usr/local/bin/kubelet \
  --config=/var/lib/kubelet/kubelet-config.yaml \
  --container-runtime=remote \
  --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock \
  --image-pull-progress-deadline=2m \
  --network-plugin=cni \
  --enable-server=false \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

echo "Enabling systemd units"
sudo systemctl daemon-reload 
sudo systemctl restart kubelet
