#!/bin/bash

set -e


mkdir -p ~/install
cd ~/install
umask 022

sudo mkdir -p /etc/cni/net.d
cat <<EOF | sudo tee /etc/cni/net.d/99-loopback.conf
{
    "cniVersion": "0.3.1",
    "type": "loopback"
}
EOF
cat <<EOF | sudo tee /etc/sysctl.d/40-kubernetes.conf
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
EOF

echo "Resetting sysctl"
sudo systemctl try-restart systemd-sysctl

echo "Loading IPVS modules"
for word in ip_vs_wrr ip_vs_sh ip_vs ip_vs_rr
do
	sudo modprobe -- $${word}
done

echo "Waiting for base package installation to complete"
cloud-init status --wait >/dev/null

echo "Installing versioned packages"

sudo apt-get -qq install \
	kubeadm=${kubernetes_release}-00 \
        kubectl=${kubernetes_release}-00 \
	kubelet=${kubernetes_release}-00

# Required because kubeadm doesn't propagate the nodeRegistration flags properly
# https://github.com/kubernetes/kubeadm/issues/1021
cat <<EOF | sudo tee /etc/default/kubelet
KUBELET_EXTRA_ARGS=--cloud-provider=external
EOF

echo "Installing bash completion"
kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl >/dev/null 2>&1

echo "Activating k8s bootstrap services"
sudo systemctl enable docker.service kubelet.service
