#!/bin/bash

set -e

create_kubeadm_config() {
	echo "Installing kubeadm.conf"
	cat <<EOF >$HOME/install/kubeadm.conf
apiVersion: kubeadm.k8s.io/v1alpha2
kubernetesVersion: ${kubernetes_release}
apiServerExtraArgs:
  cloud-provider: external
controllerManagerExtraArgs:
  cloud-provider: external
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: external
kind: MasterConfiguration
clusterName: ${cluster_name}
api:
  advertiseAddress: ${external_ip}
networking:
  dnsDomain: ${cluster_domainname}
  podSubnet: ${cluster_cidr}
  serviceSubnet: ${service_cidr}
bootstrapTokens:
  - token: ${boot_token}
apiServerCertSANs:
- ${fqdn}
- ${ipv6_fqdn}
- ${public_fqdn}
- ${public_rdns}
- ${public_ip}

kubeProxy:
  config:
    mode: ipvs
    ipvs:
      scheduler: lc
EOF
}

create_kubeadm_config
