#!/bin/bash

set -e

# Retries a command on failure.
# $1 - the max number of attempts
# $2... - the command to run
retry() {
    local max_attempts="${1}"; shift
    local attempt_num=1

    until "${@}"
    do
        if [ "${attempt_num}" -eq "${max_attempts}" ]
        then
            echo "Attempt ${attempt_num} failed and there are no more attempts l
eft!"
            return 1
        else
            echo "Attempt ${attempt_num} failed! Trying again in ${attempt_num}
seconds..."
            sleep $(( attempt_num=attempt_num + 1 ))
        fi
    done
}

spread_deployments() {
	if [ $(kubectl -n kube-system get pods -o=custom-columns=NODE:.spec.nodeName --selector=k8s-app=kube-dns --no-headers| sort -u | wc -l) -eq 1 ]
	then
		echo "Redeploying services across nodes"
		if [ $(kubectl version --client --short | grep -o '[0-9.]*') \< '1.15.0' ]
		then
			kubectl -n kube-system delete $(kubectl -n kube-system get pods -o name --selector=k8s-app=kube-dns | head -1)
		else
			retry 5 kubectl -n kube-system rollout restart deployment coredns
		fi
	fi
}

spread_deployments
