#!/bin/sh
set -e

version="${1:?Give kubernetes version as argument}"

helm_config() {
cat << 'EOF'
---
autoDiscovery:
  clusterName: "${cluster_fqdn}"
cloudProvider: brightbox
image:
  repository: "${autoscaler_repository}"
  tag: "${autoscaler_release}"
  pullPolicy: Always
nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
- effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
- operator: Exists
  key: CriticalAddonsOnly
extraArgs:
  v: '2'
  stderrthreshold: info
  logtostderr: true
  cluster-name: "${cluster_fqdn}"
  skip-nodes-with-local-storage: true
podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '8085'
rbac:
  create: true
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi
envFromSecret: brightbox-credentials
priorityClassName: system-cluster-critical
dnsPolicy: Default
EOF
}

printf "autoscaler_manifest() {\ncat <<EOF\n"
helm_config | helm template release autoscaler/cluster-autoscaler --kube-version "${version}" --namespace kube-system -f -
printf "EOF\n}\n"
