---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-pvc1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluster-test
  labels:
    app: gluster-test
spec:
  selector:
    matchLabels:
      app: gluster-test
  replicas: 3
  template:
    metadata:
      labels:
        app: gluster-test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: test-container
        image: gcr.io/google_containers/busybox:1.24
        command: 
        - "/bin/sh"
        args:
        - "-c"
        - "count=0; count_file=\"/usr/test-pod/count\"; test_file=\"/usr/test-pod/test_file\"; if [ -e $count_file ]; then count=$(cat $count_file); fi; echo $((count+1)) > $count_file; while [ 1 ]; do date >> $test_file; echo \"This is $MY_POD_NAME, count=$(cat $count_file)\" >> $test_file; sleep 10; done"
        resources:
          limits:
            cpu: 100m
            memory: 5Mi
          requests:
            cpu: 20m
            memory: 1Mi
        volumeMounts:
        - name: gluster-vol
          mountPath: /usr/test-pod
        env:
        - name: MY_POD_NAME
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name
      securityContext:
        fsGroup: 1234
      volumes:
      - name: gluster-vol
        persistentVolumeClaim: 
          claimName: "gluster-pvc1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluster-test-reader
  labels:
    app: gluster-test-reader
spec:
  selector:
    matchLabels:
      app: gluster-test-reader
  replicas: 1
  template:
    metadata:
      labels:
        app: gluster-test-reader
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: reader
        image: gcr.io/google_containers/busybox:1.24
        command: 
        - "/bin/sh"
        args:
        - "-c"
        - "tail -f /usr/test-pod/test_file"
        resources:
          limits:
            cpu: 100m
            memory: 5Mi
          requests:
            cpu: 20m
            memory: 1Mi
        volumeMounts:
        - name: gluster-vol
          mountPath: /usr/test-pod
      volumes:
      - name: gluster-vol
        persistentVolumeClaim: 
          claimName: "gluster-pvc1"
