---
apiVersion: v1
kind: Namespace
metadata:
  name: glusterfs
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: glusterfs
spec:
  ports:
  - port: 24007
    protocol: TCP
    name: control-port-1
  clusterIP: None
  selector:
    name: server
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: server
  namespace: glusterfs
  labels:
    glusterfs: deployment
spec:
  selector:
    matchLabels:
      name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      shareProcessNamespace: true
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/storage
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - server
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: glusterfs
          image: quay.io/brightbox/gluster
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: glusterfs-logs
              mountPath: /var/log/glusterfs
            - name: glusterfs-config
              mountPath: /var/lib/glusterd
            - name: glusterfs-data
              mountPath: /data
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: glusterfs-logs
          hostPath:
            path: /var/log/glusterfs
            type: DirectoryOrCreate
        - name: glusterfs-config
          hostPath:
            path: /var/lib/glusterd
            type: DirectoryOrCreate
        - name: glusterfs-data
          hostPath:
            path: /srv/export/glusterfs
            type: DirectoryOrCreate
