apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
secretGenerator:
- name: metric-server-tls
  files:
    - tls.crt
    - tls.key
  type: "kubernetes.io/tls"
resources:
- components.yaml
patchesStrategicMerge:
- deployment-additions.yaml
- apiservice-bundle.yaml
